# This file should be named after your model

# You do not have to explicitly enter objects.
# Factory Girl uses the random (fake) values generated by faker to create
# factories that will be used whenever you run your test.

FactoryGirl.define do
  factory :contact do
    full_name     { Faker::Name.name }
    email         { Faker::Internet.email }
    phone_number  { Faker::PhoneNumber.phone_number }
    address       { Faker::Address.street_address }
  end
end
